server {
    listen 80;
    server_name _;
    charset utf-8;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location ~* \.(pdf|jpg|jpeg|png|gif|svg)$ {
        add_header Cache-Control "public, max-age=86400";
    }

    location ~* \.(css|js|html)$ {
        add_header Cache-Control "no-cache";
    }
}
