server {
    listen 80;
    server_name _;
    charset utf-8;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location ~* \.(pdf|jpg|jpeg|png|gif|svg)$ {
        expires 7d;
        add_header Cache-Control "public, immutable";
    }

    location ~* \.(css|js)$ {
        expires 1d;
        add_header Cache-Control "public";
    }
}
